"""empty message

Revision ID: 02f7aef7fe96
Revises: af53a5384769
Create Date: 2025-05-25 10:20:19.598337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02f7aef7fe96'
down_revision = 'af53a5384769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_customer_country')
        batch_op.drop_column('customer_country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_country', mysql.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_order_customer_country', ['customer_country'], unique=False)

    # ### end Alembic commands ###
