"""empty message

Revision ID: 05fccde16c10
Revises: cdccd4b796a2
Create Date: 2024-12-18 16:15:03.363348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fccde16c10'
down_revision = 'cdccd4b796a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('product_style', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('product_weight', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_original_price'), ['original_price'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_style'), ['product_style'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_weight'), ['product_weight'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_product_weight'))
        batch_op.drop_index(batch_op.f('ix_product_product_style'))
        batch_op.drop_index(batch_op.f('ix_product_original_price'))
        batch_op.drop_column('product_weight')
        batch_op.drop_column('product_style')
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
