"""empty message

Revision ID: 139e9f4069c6
Revises: 12e894bf7a74
Create Date: 2024-10-29 08:33:39.208281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139e9f4069c6'
down_revision = '12e894bf7a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('review_id', sa.String(length=64), nullable=False),
    sa.Column('costumer_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('review_text', sa.String(length=280), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('review_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['costumer_id'], ['costumer.costumer_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_review_date'), ['review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_review_rating'), ['review_rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_review_text'), ['review_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_updated_at'))
        batch_op.drop_index(batch_op.f('ix_review_review_text'))
        batch_op.drop_index(batch_op.f('ix_review_review_rating'))
        batch_op.drop_index(batch_op.f('ix_review_review_date'))
        batch_op.drop_index(batch_op.f('ix_review_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_review_created_at'))

    op.drop_table('review')
    # ### end Alembic commands ###
