"""empty message

Revision ID: 3af6705ba9a9
Revises: 2bbb870d58f3
Create Date: 2024-10-29 06:25:21.739551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3af6705ba9a9'
down_revision = '2bbb870d58f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('cart_id', sa.String(length=64), nullable=False),
    sa.Column('costumer_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('cart_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['costumer_id'], ['costumer.costumer_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_cart_quantity'), ['cart_quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_bank_details')
        batch_op.drop_index('ix_order_payment_method')
        batch_op.drop_index('ix_order_shipping_address')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('bank_details')
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', mysql.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('bank_details', mysql.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('payment_method', mysql.ENUM('Credit Card', 'Debit Card', 'Paypal'), nullable=True))
        batch_op.create_index('ix_order_shipping_address', ['shipping_address'], unique=False)
        batch_op.create_index('ix_order_payment_method', ['payment_method'], unique=False)
        batch_op.create_index('ix_order_bank_details', ['bank_details'], unique=False)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_updated_at'))
        batch_op.drop_index(batch_op.f('ix_cart_created_at'))
        batch_op.drop_index(batch_op.f('ix_cart_cart_quantity'))

    op.drop_table('cart')
    # ### end Alembic commands ###
