"""empty message

Revision ID: 4f85b0d5ed1c
Revises: 6c525533505b
Create Date: 2024-12-20 09:39:51.981732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f85b0d5ed1c'
down_revision = '6c525533505b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_gemstone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('product_refference', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_product_produc_gemstone')
        batch_op.create_index(batch_op.f('ix_product_product_gemstone'), ['product_gemstone'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_refference'), ['product_refference'], unique=False)
        batch_op.drop_column('produc_gemstone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produc_gemstone', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_product_product_refference'))
        batch_op.drop_index(batch_op.f('ix_product_product_gemstone'))
        batch_op.create_index('ix_product_produc_gemstone', ['produc_gemstone'], unique=False)
        batch_op.drop_column('product_refference')
        batch_op.drop_column('product_gemstone')

    # ### end Alembic commands ###
