"""empty message

Revision ID: 5583f1053996
Revises: c4978da78f1e
Create Date: 2024-10-01 16:13:07.597808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5583f1053996'
down_revision = 'c4978da78f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=True))
        batch_op.drop_constraint('seller_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('seller_ibfk_1', 'user', ['seller_id'], ['user_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
