"""empty message

Revision ID: 852e9ec659bd
Revises: ce957ceae396
Create Date: 2024-10-26 10:43:29.311660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852e9ec659bd'
down_revision = 'ce957ceae396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('costumer_id', sa.String(length=64), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('order_status', sa.Enum('Pending', 'Delivered', 'Cancelled'), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('shipping_address', sa.String(length=64), nullable=True),
    sa.Column('payment_method', sa.Enum('Credit Card', 'Debit Card', 'Paypal'), nullable=True),
    sa.Column('bank_details', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['costumer_id'], ['costumer.costumer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_bank_details'), ['bank_details'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_order_date'), ['order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_order_status'), ['order_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_payment_method'), ['payment_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_shipping_address'), ['shipping_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_total_price'), ['total_price'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_total_quantity'), ['total_quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_updated_at'), ['updated_at'], unique=False)

    op.create_table('wishlist',
    sa.Column('wishlist_id', sa.String(length=64), nullable=False),
    sa.Column('costumer_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['costumer_id'], ['costumer.costumer_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('wishlist_id')
    )
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_updated_at'))
        batch_op.drop_index(batch_op.f('ix_wishlist_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_wishlist_created_at'))

    op.drop_table('wishlist')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_updated_at'))
        batch_op.drop_index(batch_op.f('ix_order_total_quantity'))
        batch_op.drop_index(batch_op.f('ix_order_total_price'))
        batch_op.drop_index(batch_op.f('ix_order_shipping_address'))
        batch_op.drop_index(batch_op.f('ix_order_payment_method'))
        batch_op.drop_index(batch_op.f('ix_order_order_status'))
        batch_op.drop_index(batch_op.f('ix_order_order_date'))
        batch_op.drop_index(batch_op.f('ix_order_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_order_created_at'))
        batch_op.drop_index(batch_op.f('ix_order_bank_details'))

    op.drop_table('order')
    # ### end Alembic commands ###
