"""empty message

Revision ID: 981370f0b60e
Revises: 139e9f4069c6
Create Date: 2024-10-29 08:57:27.562414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981370f0b60e'
down_revision = '139e9f4069c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_history',
    sa.Column('purchase_id', sa.String(length=64), nullable=False),
    sa.Column('costumer_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_quantity', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['costumer_id'], ['costumer.costumer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_history_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_history_purchase_date'), ['purchase_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_history_purchase_price'), ['purchase_price'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_history_purchase_quantity'), ['purchase_quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_history_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_history_updated_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_history_purchase_quantity'))
        batch_op.drop_index(batch_op.f('ix_purchase_history_purchase_price'))
        batch_op.drop_index(batch_op.f('ix_purchase_history_purchase_date'))
        batch_op.drop_index(batch_op.f('ix_purchase_history_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_history_created_at'))

    op.drop_table('purchase_history')
    # ### end Alembic commands ###
