"""empty message

Revision ID: af53a5384769
Revises: bf8374e6e888
Create Date: 2025-05-25 08:57:52.148976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af53a5384769'
down_revision = 'bf8374e6e888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('customer_state', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('customer_zip', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('customer_country', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_customer_city'), ['customer_city'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_customer_country'), ['customer_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_customer_state'), ['customer_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_customer_zip'), ['customer_zip'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_customer_zip'))
        batch_op.drop_index(batch_op.f('ix_order_customer_state'))
        batch_op.drop_index(batch_op.f('ix_order_customer_country'))
        batch_op.drop_index(batch_op.f('ix_order_customer_city'))
        batch_op.drop_column('customer_country')
        batch_op.drop_column('customer_zip')
        batch_op.drop_column('customer_state')
        batch_op.drop_column('customer_city')

    # ### end Alembic commands ###
