"""I'm here

Revision ID: b79391c0e932
Revises: 7bc325fecede
Create Date: 2024-10-14 14:17:01.625443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b79391c0e932'
down_revision = '7bc325fecede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumer', schema=None) as batch_op:
        batch_op.alter_column('costumer_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumer', schema=None) as batch_op:
        batch_op.alter_column('costumer_id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
