"""empty message

Revision ID: bf8374e6e888
Revises: dee143cf4c0b
Create Date: 2025-05-25 08:51:04.887518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8374e6e888'
down_revision = 'dee143cf4c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('customer_address', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_customer_address'), ['customer_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_customer_email'), ['customer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_customer_name'), ['customer_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_customer_phone'), ['customer_phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_customer_phone'))
        batch_op.drop_index(batch_op.f('ix_order_customer_name'))
        batch_op.drop_index(batch_op.f('ix_order_customer_email'))
        batch_op.drop_index(batch_op.f('ix_order_customer_address'))
        batch_op.drop_column('customer_address')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
