"""empty message

Revision ID: c4978da78f1e
Revises: ff31cbaaef09
Create Date: 2024-10-01 16:08:06.702036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4978da78f1e'
down_revision = 'ff31cbaaef09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_seller_store_address')
        batch_op.create_index(batch_op.f('ix_seller_address'), ['address'], unique=False)
        batch_op.drop_column('store_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_address', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_seller_address'))
        batch_op.create_index('ix_seller_store_address', ['store_address'], unique=False)
        batch_op.drop_column('address')

    # ### end Alembic commands ###
