"""empty message

Revision ID: cdccd4b796a2
Revises: 61f71334d406
Create Date: 2024-12-16 12:29:04.956793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdccd4b796a2'
down_revision = '61f71334d406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_material', sa.Enum('Gold', 'Silver', 'Platinum', 'Diamond', 'Pearl', 'Emerald', 'Ruby', 'Sapphire'), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_product_material'), ['product_material'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_product_material'))
        batch_op.drop_column('product_material')

    # ### end Alembic commands ###
