"""empty message

Revision ID: ce957ceae396
Revises: b79391c0e932
Create Date: 2024-10-17 15:30:03.345147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce957ceae396'
down_revision = 'b79391c0e932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('seller_id', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.Column('product_description', sa.String(length=120), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=True),
    sa.Column('product_quantity', sa.Integer(), nullable=True),
    sa.Column('product_status', sa.Enum('Available', 'Unavailable'), nullable=True),
    sa.Column('product_category', sa.String(length=64), nullable=True),
    sa.Column('product_image', sa.String(length=120), nullable=True),
    sa.Column('product_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.seller_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_category'), ['product_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_description'), ['product_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_image'), ['product_image'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_name'), ['product_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_price'), ['product_price'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_quantity'), ['product_quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_rating'), ['product_rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_product_status'), ['product_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_updated_at'))
        batch_op.drop_index(batch_op.f('ix_product_product_status'))
        batch_op.drop_index(batch_op.f('ix_product_product_rating'))
        batch_op.drop_index(batch_op.f('ix_product_product_quantity'))
        batch_op.drop_index(batch_op.f('ix_product_product_price'))
        batch_op.drop_index(batch_op.f('ix_product_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_product_image'))
        batch_op.drop_index(batch_op.f('ix_product_product_description'))
        batch_op.drop_index(batch_op.f('ix_product_product_category'))
        batch_op.drop_index(batch_op.f('ix_product_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_product_created_at'))

    op.drop_table('product')
    # ### end Alembic commands ###
