"""Add payment_method and payment_status to Order model

Revision ID: dee143cf4c0b
Revises: db3d2931090b
Create Date: 2025-05-25 06:58:23.587555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee143cf4c0b'
down_revision = 'db3d2931090b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.Enum('paid', 'pending', 'failed'), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_payment_method'), ['payment_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_payment_status'), ['payment_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_payment_status'))
        batch_op.drop_index(batch_op.f('ix_order_payment_method'))
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
