"""empty message

Revision ID: ff31cbaaef09
Revises: 
Create Date: 2024-09-30 21:24:21.869576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff31cbaaef09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller',
    sa.Column('seller_id', sa.String(length=64), nullable=False),
    sa.Column('store_name', sa.String(length=64), nullable=True),
    sa.Column('store_address', sa.String(length=64), nullable=True),
    sa.Column('store_description', sa.String(length=120), nullable=True),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('bank_account', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('seller_status', sa.Enum('Active', 'Inactive'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('seller_id')
    )
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seller_bank_account'), ['bank_account'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_license_number'), ['license_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_seller_status'), ['seller_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_store_address'), ['store_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_store_description'), ['store_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_store_name'), ['store_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_updated_at'))
        batch_op.drop_index(batch_op.f('ix_seller_store_name'))
        batch_op.drop_index(batch_op.f('ix_seller_store_description'))
        batch_op.drop_index(batch_op.f('ix_seller_store_address'))
        batch_op.drop_index(batch_op.f('ix_seller_seller_status'))
        batch_op.drop_index(batch_op.f('ix_seller_phone_number'))
        batch_op.drop_index(batch_op.f('ix_seller_license_number'))
        batch_op.drop_index(batch_op.f('ix_seller_is_verified'))
        batch_op.drop_index(batch_op.f('ix_seller_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_seller_created_at'))
        batch_op.drop_index(batch_op.f('ix_seller_bank_account'))

    op.drop_table('seller')
    # ### end Alembic commands ###
